# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 04:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay_per_hour',
            name='type',
        ),
        migrations.RemoveField(
            model_name='employee_department',
            name='employee_dep',
        ),
        migrations.RemoveField(
            model_name='employee_type',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_dep',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='payroll.Employee_department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='payroll.Employee_type'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Pay_per_hour',
        ),
    ]
